name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v2.3.5
      with:
          lfs: false
    # Build Image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
