name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout Super-Florida-Man repo
    - uses: actions/checkout@v2.3.5
      with:
          lfs: false
          path: "sfm"
    # Checkout Unreal Engine repo
    - uses: actions/checkout@v2.3.5
      with:
          lfs: false
          path: "ue4"
          repository: "EpicGames/UnrealEngine"
          ref: "4.27"
          token: ${{ secrets.GH_TOKEN }}
    # Build Unreal Engine
    - run: "./ue4/Setup.sh"
