name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v2.3.5
      with:
          lfs: false
    # Step 2
    - run: sudo pip3 install ue4-docker
