name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout Super-Florida-Man
    - uses: actions/checkout@v2.3.5
      with:
          lfs: false
          path: "sfm"
    # Docker Login
    - run: "echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ secrets.GH_USERNAME }} --password-stdin"
