name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
    # Log Disk Usage
    - run: "df -h"
    # Cleanup Disk Space
    - uses: easimon/maximize-build-space@v4
      with:
        root-reserve-mb: 46080
        swap-size-mb: 1024
        remove-dotnet: "true"
        remove-android: "true"
        remove-haskell: "true"
    # Log Disk Usage
    - run: "df -h"
    # Checkout Super-Florida-Man
    - uses: actions/checkout@v2.3.5
      with:
          lfs: false
          
    # Docker Run
    - uses: addnab/docker-run-action@v2
      with:
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: ghcr.io
        image: ghcr.io/epicgames/unreal-engine:dev-4.27
        options: -v ${{ github.workspace }}:/project
        run: |
          find . -maxdepth 2 -type d ;\
          chown -R `whoami` project/ ;\
          chmod -R u+rw project/ ;\
          /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh \
          BuildCookRun \
          -utf8output \
          -platform=Linux \
          -clientconfig=Shipping \
          -serverconfig=Shipping \
          -project=/project/Super_Florida_Man.uproject \
          -noP4 -nodebuginfo -allmaps \
          -cook -build -stage -prereqs -pak -archive \
          -archivedirectory=/project/Packaged 

    # Log Disk Usage
    - run: "df -h"
    # Log Directories
    - run: "find . -maxdepth 2 -type d"
    # Upload
    - uses: actions/upload-artifact@v2.1.4
      with:
        name: Build
        path: project
