name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v2.3.5
      with:
          lfs: false
    # Install ue4-docker
    - run: sudo pip3 install ue4-docker
    # Create Unreal Engine image
    - run: ue4-docker build 4.20.3
