name: Build

# Required Secrets
# DOCKER_USERNAME
# DOCKER_TOKEN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
defaults:
  run:
    shell: powershell

env:
  IMAGE_TAG: exanite/exanite:unreal-engine-4.27.0-ltsc2019-windows-ddc

jobs:
  # Build
  build:
    name: Build for ${{ matrix.PLATFORM }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
       PLATFORM:
       - Win64
     # - Linux
     # - Mac
    steps:
    
    # Login to Docker
    - name: Login to Docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

    # Checkout Super-Florida-Man
    - name: Checkout Super-Florida-Man
      uses: actions/checkout@v2.3.5
      with:
          lfs: false
    
    # Build Game
    - name: Build Game
      run: | 
        docker run -v ${{ github.workspace }}:C:\Project `
        ${{ env.IMAGE_TAG }} `
        powershell "cd Project ; ue4 package Shipping -platform=${{ matrix.PLATFORM }}"
          
    # Upload Game
    - name: Upload Game
      uses: actions/upload-artifact@v2.1.4
      with:
        name: Build-Win64
        path: dist
