name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build
  build:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    
    # Log Disk Usage
    - name: Log Disk Usage
      run: df -h
      
    # Cleanup Disk Space
    - name: Cleanup Disk Space
      uses: easimon/maximize-build-space@v4
      with:
        root-reserve-mb: 46080
        swap-size-mb: 1024
        remove-dotnet: "true"
        remove-android: "true"
        remove-haskell: "true"
        
    # Log Disk Usage
    - name: Log Disk Usage
      run: df -h
      
    # Checkout Super-Florida-Man
    - name: Checkout Super-Florida-Man
      uses: actions/checkout@v2.3.5
      with:
          lfs: false
    
    # Restore Derived Data Cache
    - name: Restore Derived Data Cache
      id: cache-ddc
      uses: actions/cache@v2.1.6
      with:
        path: DerivedDataCache
        key: DerivedDataCache
        restore-keys: |
          - DerivedDataCache
    
    # Ensure Read-Write Permissions
    - name: Ensure Read-Write Permissions
      run: chmod -R 777 .
      
    # Generage Derived Data Cache
    - name: Build Game
      if: steps.cache-ddc.outputs.cache-hit != 'true'
      uses: addnab/docker-run-action@v2
      with:
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: ghcr.io
        image: ghcr.io/epicgames/unreal-engine:dev-4.27
        options: -v ${{ github.workspace }}:/project
        run: |
          /home/ue4/UnrealEngine/Engine/Binaries/Linux/UE4Editor \
          Super-Florida-Man -run=DerivedDataCache -fill -DDC=CreatePak \
          -buildmachine -stdout -unattended -nopause -nullrhi -nosplash
    
    # Build Game
    - name: Build Game
      uses: addnab/docker-run-action@v2
      with:
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
        registry: ghcr.io
        image: ghcr.io/epicgames/unreal-engine:dev-4.27
        options: -v ${{ github.workspace }}:/project
        run: |
          /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh \
          BuildCookRun \
          -utf8output \
          -platform=Linux \
          -clientconfig=Shipping \
          -serverconfig=Shipping \
          -project=/project/Super_Florida_Man.uproject \
          -noP4 -nodebuginfo -allmaps \
          -cook -build -stage -prereqs -pak -archive \
          -archivedirectory=/project/Packaged 

    # Log Disk Usage
    - name: Log Disk Usage
      run: df -h
    
    # Upload
    - uses: actions/upload-artifact@v2.1.4
      with:
        name: Build
        path: Packaged
