name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout Super-Florida-Man
    - uses: actions/checkout@v2.3.5
      with:
          lfs: false
          path: "sfm"
    # Log Disk Usage
    - run: "df -h"
    # Cleanup Disk Space
    - uses: easimon/maximize-build-space@v4
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: "true"
        remove-android: "true"
        remove-haskell: "True"
    # Log Disk Usage
    - run: "df -h"
    # Docker Login
    - run: "echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ secrets.GH_USERNAME }} --password-stdin"
    # Pull Unreal Engine Image
    - run: "docker pull ghcr.io/epicgames/unreal-engine:dev-4.27"
    # Build Project
    - run: "docker run --rm -ti -v \"PROJECT_PATH:/project\" ghcr.io/epicgames/unreal-engine:dev-4.27"
